# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  app1:
    adapter: mysql2
    encoding: utf8
    reconnect: false
    database: app1_development
    pool: 5
    username: root
    password:
    socket: /tmp/mysql.sock
    host: 127.0.0.1
  app2:
    adapter: mysql2
    encoding: utf8
    reconnect: false
    database: app2_development
    pool: 5
    username: root
    password:
    socket: /tmp/mysql.sock
    host: 127.0.0.1

test:
  app1:
    adapter: mysql2
    encoding: utf8
    reconnect: false
    database: app1_development_test
    pool: 5
    username: root
    password:
    socket: /tmp/mysql.sock
    host: 127.0.0.1
  app2:
    adapter: mysql2
    encoding: utf8
    reconnect: false
    database: app2_development_test
    pool: 5
    username: root
    password:
    socket: /tmp/mysql.sock
    host: 127.0.0.1

production:
  <<: *default
  database: storage/production.sqlite3
